CREATE TABLE IF NOT EXISTS groupPosts (
		id INTEGER PRIMARY KEY,
		group_id INTEGER NOT NULL,
		author_id INTEGER NOT NULL,
		content TEXT NOT NULL,
		image TEXT DEFAULT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
		FOREIGN KEY (author_id) REFERENCES user(id) ON DELETE CASCADE
	);